<?php

/**
 * Contains hardcoded list of migrates, for ease of use.
 *
 * @return array
 */
function _rocketship_demo_config_migrates() {
  return [
    'rocketship_demo_config_images',
    'rocketship_demo_config_media_images',
    'rocketship_demo_config_p_002',
    'rocketship_demo_config_p_003',
    'rocketship_demo_config_blocks',
    'rocketship_demo_config_socials',
    'rocketship_demo_config_usp_block',
    'rocketship_demo_config_site_branding',
    'rocketship_demo_config_menu_links',
  ];
}

/**
 * Implements hook_migration_plugins_alter().
 */
function rocketship_demo_config_migration_plugins_alter(&$definitions) {
  $path = drupal_get_path('module', 'rocketship_demo_config');

  foreach (_rocketship_demo_config_migrates() as $name) {
    $definitions[$name]['source']['path'] = $path . $definitions[$name]['source']['path'];
  }

  $definitions['rocketship_demo_config_images']['source']['constants']['source_base_path'] = $path . $definitions['rocketship_demo_config_images']['source']['constants']['source_base_path'];
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure we go after migrate_plus.
 */
function rocketship_demo_config_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'migration_plugins_alter') {
    $group = $implementations['rocketship_demo_config'];
    unset($implementations['rocketship_demo_config']);
    $implementations['rocketship_demo_config'] = $group;
  }
  if ($hook == 'themes_installed') {
    $group = $implementations['rocketship_demo_config'];
    unset($implementations['rocketship_demo_config']);
    $implementations['rocketship_demo_config'] = $group;
  }
}

/**
 * Implements hook_themes_installed().
 */
function rocketship_demo_config_themes_installed($theme_list) {
  /** @var \Drupal\Core\Extension\ThemeHandlerInterface $handler */
  $handler = Drupal::service('theme_handler');

  foreach ($theme_list as $theme) {
    $info = $handler->getTheme($theme);
    if (isset($info->info['package']) && $info->info['package'] == 'Rocketship Theme') {
      rocketship_demo_config_place_default_blocks($info);
    }
  }
}

/**
 * Place our blocks in the correct region of the provided theme.
 *
 * @param \Drupal\Core\Extension\Extension $theme
 *   Theme name.
 */
function rocketship_demo_config_place_default_blocks($theme) {
  $regions = $theme->info['regions'];

  if (isset($regions['doormat_03'])) {
    Rocketship::placeBlock('block_content:55da64d2-ed75-4038-9df0-8ec57fb06516', [
        'region' => 'doormat_03',
        'theme' => $theme->getName(),
        'label' => 'Social',
        'provider' => 'block_content',
        'label_display' => 'visible',
        'status' => TRUE,
        'info' => '',
        'id' => 'socials-55da64d2-ed75-4038-9df0-8ec57fb06516',
      ]
    );
  }

  if (isset($regions['doormat'])) {
    Rocketship::placeBlock('block_content:3fcb9e7e-22a2-49b4-bbad-08bd619bc81e', [
        'region' => 'doormat',
        'theme' => $theme->getName(),
        'label' => 'Site branding',
        'provider' => 'block_content',
        'label_display' => 0,
        'status' => TRUE,
        'info' => '',
        'id' => 'sitebranding-3fcb9e7e-22a2-49b4-bbad-08bd619bc81e',
      ]
    );
  }

  if (isset($regions['doormat_02'])) {
    Rocketship::placeBlock('system_menu_block:main', [
        'region' => 'doormat_02',
        'theme' => $theme->getName(),
        'label' => 'Sitemap',
        'provider' => 'system',
        'label_display' => 'visible',
        'level' => 1,
        'depth' => 1,
        'expand_all_items' => FALSE,
        'status' => TRUE,
      ]
    );
  }

}
