variant_settings:
  blocks:
    d679bf78-cdbf-40f9-8859-ca72c1786b19:
      id: 'block_content:d679bf78-cdbf-40f9-8859-ca72c1786b19'
      label: 'Homepage Image'
      provider: block_content
      label_display: '0'
      status: true
      info: ''
      view_mode: full
      region: visual
      weight: -4
      uuid: d679bf78-cdbf-40f9-8859-ca72c1786b19
      context_mapping: {  }
    f5d5bfc4-6a03-4756-b7a5-c3ad29da3095:
      id: 'block_content:f5d5bfc4-6a03-4756-b7a5-c3ad29da3095'
      label: 'USP Homepage'
      provider: block_content
      label_display: '0'
      status: true
      info: ''
      view_mode: full
      region: header
      weight: -3
      uuid: f5d5bfc4-6a03-4756-b7a5-c3ad29da3095
      context_mapping: {  }
    78dd02b1-c1e2-4a8a-bc31-f4b8ad7672f3:
      id: 'block_content:78dd02b1-c1e2-4a8a-bc31-f4b8ad7672f3'
      label: 'About us'
      provider: block_content
      label_display: '0'
      status: true
      info: ''
      view_mode: full
      region: header
      weight: -2
      uuid: 78dd02b1-c1e2-4a8a-bc31-f4b8ad7672f3
      context_mapping: {  }
